apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-rest-api
  annotations:
    deployment.kubernetes.io/desired-replicas: "3"
    deployment.kubernetes.io/max-replicas: "20"
    deployment.kubernetes.io/revision: "3"

spec:
  selector:
    matchLabels:
      app: springboot-rest-api
  replicas: 3
  template:
    metadata:
      labels:
        app: springboot-rest-api
    spec:
      containers:
        - name: springboot-rest-api
          image: verranm/rest-api:testing
          ports:
            - containerPort: 9090
              name: "http"
          resources:
            limits:
              memory: 2Gi
              cpu: "2"
      readinessProbe:
        failureThreshold: 3
        httpGet:
          path: /api/books
          port: 9090
          scheme: HTTP
        initialDelaySeconds: 5
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1

