---
apiVersion: v1
kind: Service
metadata:
  name: springboot-rest-api-svc
  namespace: applications
spec:
  selector:
    app: springboot-rest-api
  ports:
    - port: 9090
      name: http-springboot-rest-api
  type: LoadBalancer
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: springboot-rest-api-gateway
  namespace: applications
spec:
  gatewayClassName: istio
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 9090
      name: http
      protocpl: http
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: springboot-rest-api-vs
  namespace: applications
spec:
  hosts:
  - *
  gateways:
  - applications/springboot-rest-api-gateway 
  http:
  - match:
    - uri:
        regex: "*/springboot-rest-api*"
    route:
    - destination:
        host: "springboot-rest-api-svc"
        port:
          number: 9090       
