---
apiVersion: v1
kind: Service
metadata:
  name: springboot-rest-api-svc
  namespace: applications
spec:
  selector:
    app: springboot-rest-api
  ports:
    - port: 9090
      name: http-springboot-rest-api
  type: LoadBalancer
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: springboot-rest-api-gateway
  namespace: applications
spec:
  gatewayClassName: istio
  listeners:
  - name: http
    port: 9090
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: Same
---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: springboot-rest-api-vs
  namespace: applications
spec:
  hosts:
  - springboot-rest-api.applications.svc.cluster.local
  gateways:
  - applications/springboot-rest-api-gateway 
  tcp:
  - match:
    - port: 9090
    route:
    - destination:
        host: springboot-rest-api.applications.svc.cluster.local
        port:
          number: 9090       
