---
apiVersion: v1
kind: Service
metadata:
  name: springboot-rest-api-svc
  namespace: applications
spec:
  selector:
    app: springboot-rest-api
  ports:
    - port: 8080
      name: http-springboot-rest-api
  type: LoadBalancer
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: springboot-rest-api-gateway
  namespace: applications
spec:
  gatewayClassName: istio
  listeners:
  - name: http
    port: 8080
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: Same
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: springboot-rest-api-httproute
  namespace: applications
spec:
  parentRefs:
  - name: springboot-rest-api-gateway
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /springboot-rest-api
    filters:
    - type: URLRewrite
      urlRewrite:
        path:
          type: ReplaceFullPath
          replaceFullPath: /
    backendRefs:
    - name: springboot-rest-api-svc
      port: 8080
